Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,25 +1,34 @@
-name: Sync Fork
+name: Upstream Sync
+
+permissions:
+    contents: write
 
 on:
-  schedule:
-    - cron: '0 0 * * *'  # 每天午夜 00:00 执行一次同步
-  workflow_dispatch:  # 允许手动触发工作流
+    schedule:
+        - cron: "0 0 * * *"
+    workflow_dispatch:
 
 jobs:
-  sync:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+    sync_with_upstream:
+        name: Sync with Upstream
+        runs-on: ubuntu-latest
+        if: ${{ github.event.repository.fork }}
 
-      - name: Add upstream remote
-        run: git remote add upstream https://github.com/imzyb/MiSub.git
+        steps:
+            - name: Checkout target repo
+              uses: actions/checkout@v3
 
-      - name: Fetch upstream changes
-        run: git fetch upstream
+            - name: Sync Upstream
+              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+              with:
+                  target_repo_token: ${{ secrets.GITHUB_TOKEN }}
+                  upstream_sync_repo: HackJava/HackJava
+                  upstream_sync_branch: main
+                  target_sync_branch: main
+                  test_mode: false
 
-      - name: Merge upstream changes
-        run: git merge upstream/main --allow-unrelated-histories -m "Sync with upstream"
-
-      - name: Push changes
-        run: git push origin main
+            - name: Check for Failure
+              if: failure()
+              run: |
+                  echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
+                  exit 1
